### PR TITLE
test

### PR DESCRIPTION
**Pull request by sarah-lucca**

### CODE REVIEW

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
atlantis plan

**Comment by sarah97** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default": exit status 1

Initializing the backend...
Error configuring the backend "s3": 2 error(s) occurred:

* "bucket": required field is not set
* "key": required field is not set

```

**Comment by sarah-lucca** [comment]
atlantis plan -backend-config=config/personal.conf

**Comment by sarah-lucca** [comment]
```
Error: unknown shorthand flag: 'b' in -backend-config=config/personal.conf.
Usage of plan:
  -d, --dir string         Which directory to run plan in relative to root of repo,
                           ex. 'child/dir'.
  -p, --project string     Which project to run plan for. Refers to the name of the
                           project configured in atlantis.yaml. Cannot be used at
                           same time as workspace or dir flags.
      --verbose            Append Atlantis log to comment.
  -w, --workspace string   Switch to this Terraform workspace before planning.
```

**Comment by sarah-lucca** [comment]
atlantis plan -- -backend-config=config/personal.conf

**Comment by sarah-lucca** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default": exit status 1

Initializing the backend...
Error configuring the backend "s3": 2 error(s) occurred:

* "bucket": required field is not set
* "key": required field is not set

```

**Comment by sarah-lucca** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform init -input=false -no-color -upgrade" in "/Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default": exit status 1

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error loading state: AccessDenied: Access Denied
	status code: 403, request id: DA93D1C14FCF1264, host id: znNlaCUXLPnuDlIl+Bv55ybwPeFn66OxNrQCRjgVSa+nzEhR2NG6HP8TNvaxE6XQ0jtkv3KQR+A=

```

**Comment by sarah-lucca** [comment]
**Plan Error**
```
atlantis.yaml files not allowed because Atlantis is not running with --allow-repo-config
```

**Comment by sarah-lucca** [comment]
atlantis plan

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

```diff

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
atlantis plan -p test

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

```diff

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
**Plan Error**
```
parsing atlantis.yaml: yaml: unmarshal errors:
  line 14: cannot unmarshal !!map into string
```

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
[0m[1mRefreshing Terraform state in-memory prior to plan...[0m
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
[0m

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[32m  [32m+[0m [32maws_s3_bucket.atlantis_test_bucket
[0m      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "slucca-atlantis-test-bucket"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "false"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>
[0m
[0m
[0m[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
atlantis apply -p test

**Comment by sarah-lucca** [comment]
Ran Apply for project: `test` dir: `.` workspace: `default`

**Apply Error**
```
no plan found at path "." and workspace "default"–did you run plan?

```

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
[0m[1mRefreshing Terraform state in-memory prior to plan...[0m
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
[0m

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[32m  [32m+[0m [32maws_s3_bucket.atlantis_test_bucket
[0m      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "slucca-atlantis-test-bucket"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "false"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>
[0m
[0m
[0m[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

This plan was saved to: /Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default/test-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default/test-default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
atlantis apply -p test

**Comment by sarah-lucca** [comment]
Ran Apply for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
[0m[1maws_s3_bucket.atlantis_test_bucket: Creating...[0m
  acceleration_status:         "" => "<computed>"
  acl:                         "" => "private"
  arn:                         "" => "<computed>"
  bucket:                      "" => "slucca-atlantis-test-bucket"
  bucket_domain_name:          "" => "<computed>"
  bucket_regional_domain_name: "" => "<computed>"
  force_destroy:               "" => "false"
  hosted_zone_id:              "" => "<computed>"
  region:                      "" => "<computed>"
  request_payer:               "" => "<computed>"
  versioning.#:                "" => "<computed>"
  website_domain:              "" => "<computed>"
  website_endpoint:            "" => "<computed>"[0m
[0m[1maws_s3_bucket.atlantis_test_bucket: Creation complete after 2s (ID: slucca-atlantis-test-bucket)[0m[0m
[0m[1m[32m
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.[0m

```
</details>

**Comment by sarah-lucca** [comment]
atlantis plan -p test

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
[0m[1mRefreshing Terraform state in-memory prior to plan...[0m
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
[0m

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[32m  [32m+[0m [32maws_s3_bucket.atlantis_test_bucket
[0m      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "slucca-atlantis-test-bucket"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "false"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>
[0m
[0m
[0m[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

This plan was saved to: /Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default/test-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default/test-default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by sarah-lucca** [comment]
atlantis plan

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
[0m[1mRefreshing Terraform state in-memory prior to plan...[0m
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
[0m

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  [32m+[0m create
[0m
Terraform will perform the following actions:

[32m  [32m+[0m [32maws_s3_bucket.atlantis_test_bucket
[0m      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "slucca-atlantis-test-bucket"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "false"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>
[0m
[0m
[0m[1mPlan:[0m 1 to add, 0 to change, 0 to destroy.[0m

------------------------------------------------------------------------

This plan was saved to: /Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default/test-default.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/Users/slucca/.atlantis/repos/sarah97/atlantis-test/1/default/test-default.tfplan"


```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
hi

**Comment by sarah-lucca** [comment]
atlantis plan -p test

**Comment by sarah-lucca** [comment]
**Plan Error**
```
the default workspace is currently locked by another command that is running for this pull request–wait until the previous command is complete and try again
```

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
[0m[1mRefreshing Terraform state in-memory prior to plan...[0m
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
[0m
[0m[1maws_s3_bucket.atlantis_test_bucket: Refreshing state... (ID: slucca-atlantis-test-bucket-1)[0m

------------------------------------------------------------------------

[0m[1m[32mNo changes. Infrastructure is up-to-date.[0m[32m

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.[0m

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
Ran Plan for project: `test` dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
[0m[1mRefreshing Terraform state in-memory prior to plan...[0m
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
[0m
[0m[1maws_s3_bucket.atlantis_test_bucket: Refreshing state... (ID: slucca-atlantis-test-bucket-1)[0m

------------------------------------------------------------------------

[0m[1m[32mNo changes. Infrastructure is up-to-date.[0m[32m

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.[0m

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -p test`
* :put_litter_in_its_place: To **delete** this plan click [here](https://localhost:4141/lock?id=sarah97%252Fatlantis-test%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -p test`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by sarah-lucca** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
